Use bash for exec so brace expansion works
exec defaults to `sh` on my machine, which does not support brace
expansion:

```plaintext
Error: Command failed: find /home/noah/dev/memfault/memfault-docs/{docs,blog} -path '**/*.mdx' -type f -exec sed -i -e '/-min.png/! s/\.png/-min.png/g' {} \;
find: ‘/home/noah/dev/memfault/memfault-docs/{docs,blog}’: No such file or directory
```

Explictly select `bash` so it works.

Interestingly, the env vars (including `$SHELL`) are passed to the
subshell:

```bash
❯ node -e 'const { exec } = require("child_process"); exec("echo \$SHELL yol{o,3}; ps -p $$", (err, stdout, stderr) => { console.log("output:\n", stdout, stderr); });'
output:
 /usr/bin/zsh yol{o,3}
    PID TTY          TIME CMD
1327281 pts/2    00:00:00 sh
```